[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.bold]
family = "JetBrainsMono NL"
#family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono NL"
#family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono NL"
#family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono NL"
#family = "JetBrainsMono Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

[scrolling]
history = 50000

[window]
opacity = 0.9
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.dimensions]
columns = 140
lines = 30
#columns = 145
#lines = 35

[window.padding]
x = 6
y = 6

[general]
import = [
    "~/.config/alacritty/themes/catppuccin-mocha.toml"
    #"~/.config/alacritty/themes/catppuccin-frappe.toml"
    #"~/.config/alacritty/themes/catppuccin-latte.toml"
    #"~/.config/alacritty/themes/catppuccin-macchiato.toml"
    #"~/.config/alacritty/themes/dracula.toml"
]
